SWC-7164: SRC FullWidthAlert updates
Sage-Bionetworks/synapse-web-monorepo pull request #1448
Opened 2024-12-06 17:47 UTC by kianamcc

Jira ticket: https://sagebionetworks.jira.com/browse/SWC-7164

<img width="356" alt="Screenshot 2024-12-05 at 11 17 39 PM" src="https://github.com/user-attachments/assets/4f2c8a61-849e-4555-b958-8d733627fc4c">

2024-12-06 17:52 UTC, kianamcc commented on packages/synapse-react-client/src/components/FullWidthAlert/FullWidthAlert.tsx
> +  const isMobile = useMediaQuery(theme.breakpoints.down('sm'))
I use useMediaQuery to handle code with conditional rendering

2024-12-06 21:27 UTC, nickgros requested changes

2024-12-06 21:27 UTC, nickgros commented on packages/synapse-react-client/src/components/FullWidthAlert/FullWidthAlert.tsx
> +          ) : (
This is a bad idea, not everywhere that we use FullWidthAlert do we guarantee that we show a title, or that the title/description by itself is enough for the user to understand what's going on.

Let's revert this part of the change and decide if we should change only the instance of the alert shown in the design, or if we should do a comprehensive review of all places where we use this component.

2024-12-06 21:27 UTC, nickgros commented on packages/synapse-react-client/src/components/FullWidthAlert/FullWidthAlert.tsx
> +            }}
These seem ok, but I want to try them out in a story to verify

2024-12-11 21:36 UTC, nickgros commented on packages/synapse-react-client/src/components/FullWidthAlert/FullWidthAlert.tsx
> +              width: { xs: '100%', sm: 'initial' },
What do you think of adding this to make the buttons expand to full width at small screen sizes?
```suggestion
              width: { xs: '100%', sm: 'initial' },
              [theme.breakpoints.down('xs')]: {
                ["& > *"]: {
                  flexGrow: 1
                }
              }
```

2024-12-11 21:37 UTC, nickgros commented on packages/synapse-react-client/src/components/FullWidthAlert/FullWidthAlert.tsx
> +            sx={{
```suggestion
            sx={theme => ({
```

2024-12-11 21:37 UTC, nickgros commented on packages/synapse-react-client/src/components/FullWidthAlert/FullWidthAlert.tsx
> +            }}
```suggestion
            })}
```

2024-12-12 13:24 UTC, nickgros approved these changes

2024-12-12 17:48 UTC, merged